name: absence_tracker
description: "A new Flutter project."
publish_to: "none" # Projet privé, ne sera pas publié

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4
  file_picker: ^10.3.7
  csv: ^6.0.0
  path: ^1.8.4
  fl_chart: ^1.1.1

  # Base de données SQLite
  #sqflite: ^2.3.0
  #path: ^1.9.0            # pour DatabaseHelper

  # State management
  provider: ^6.0.6

  # Cupertino Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets et polices (optionnel, à compléter si besoin)
  # assets:
  #   - images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
